🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/draw_img b/bin/draw_img
--- a/bin/draw_img
+++ b/bin/draw_img
@@ -1,77 +1,116 @@
 #!/usr/bin/env bash
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 PROG="draw_img"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
-
+SRC_DIR="${BASH_SOURCE%/*}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 021020210301-git
+##@Version       : 031520211720-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
-# @License       : LICENSE.md
-# @ReadME        : README.md
+# @License       : WTFPL
+# @ReadME        : draw_img --help
 # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Saturday, Mar 06, 2021 02:52 EST
+# @Created       : Monday, Mar 15, 2021 17:20 EDT
 # @File          : draw_img
 # @Description   : lf image preview script
 # @TODO          :
 # @Other         :
 # @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-clear_screen() { printf '\e[%sH\e[9999C\e[1J%b\e[1;%sr' "$((LINES - 2))" "${TMUX:+\e[2J}" "$max_items"; }
-
-# Get a file's mime_type.
-mime_type=$(file -bi "$1")
-
-# File isn't an image file, give warning.
-if [[ $mime_type != image/* ]]; then
-  lf -remote "send $id echoerr 'Not an image'"
-  exit
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
+else
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
 fi
-
-w3m_paths=(/usr/{local/,}{lib,libexec,lib64,libexec64}/w3m/w3mi*)
-read -r w3m _ < <(type -p w3mimgdisplay "${w3m_paths[@]}")
-read -r LINES COLUMNS < <(stty size)
-
-# Get terminal window size in pixels and set it to WIDTH and HEIGHT.
-export $(xdotool getactivewindow getwindowgeometry --shell)
-
-# Get the image size in pixels.
-read -r img_width img_height < <("$w3m" <<<"5;${CACHE:-$1}")
-
-((img_width > WIDTH)) && {
-  ((img_height = img_height * WIDTH / img_width))
-  ((img_width = WIDTH))
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# helper function
+__version() { app_version; }
+__help() {
+  app_help "Usage: draw_img  -  draw_img --version"  \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
 }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function
+main() {
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  case $1 in
+    -v | --version) __version ;;
+    -h | --help) __help ;;
+  esac
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Required app check
+  cmd_exists --error bash lf xdotool w3m || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  clear_screen() { printf '\e[%sH\e[9999C\e[1J%b\e[1;%sr' "$((LINES - 2))" "${TMUX:+\e[2J}" "$max_items"; }
+  # Get a file's mime_type.
+  mime_type=$(file -bi "$1")
 
-((img_height > HEIGHT)) && {
-  ((img_width = img_width * HEIGHT / img_height))
-  ((img_height = HEIGHT))
+  # File isn't an image file, give warning.
+   if [[ $mime_type != image/* ]]; then
+    lf -remote "send $id echoerr 'Not an image'"
+    exit
+  fi
+
+  w3m_paths=(/usr/{local/,}{lib,libexec,lib64,libexec64}/w3m/w3mi*)
+  read -r w3m _ < <(type -p w3mimgdisplay "${w3m_paths[@]}")
+  read -r LINES COLUMNS < <(stty size)
+
+  # Get terminal window size in pixels and set it to WIDTH and HEIGHT.
+  export $(xdotool getactivewindow getwindowgeometry --shell)
+
+  # Get the image size in pixels.
+  read -r img_width img_height < <("$w3m" <<<"5;${CACHE:-$1}")
+
+  ((img_width > WIDTH)) && {
+    ((img_height = img_height * WIDTH / img_width))
+    ((img_width = WIDTH))
+  }
+
+  ((img_height > HEIGHT)) && {
+    ((img_width = img_width * HEIGHT / img_height))
+    ((img_height = HEIGHT))
+  }
+
+  # Variable needed for centering image.
+  HALF_HEIGHT=$(expr $HEIGHT / 2)
+  HALF_WIDTH=$(expr $WIDTH / 2)
+  HALF_IMG_HEIGHT=$(expr $img_height / 2)
+  HALF_IMG_WIDTH=$(expr $img_width / 2)
+  X_POS=$(expr $HALF_WIDTH - $HALF_IMG_WIDTH)
+  Y_POS=$(expr $HALF_HEIGHT - $HALF_IMG_HEIGHT)
+
+  clear_screen
+  # Hide the cursor.
+  printf '\e[?25l'
+
+  # Display the image.
+printf '0;1;%s;%s;%s;%s;;;;;%s\n3;\n4\n' ${X_POS:-0} ${Y_POS:-0} "$img_width" "$img_height" "${CACHE:-$1}" | \
+  "$w3m" &>/dev/null
+  # Wait for user input.
+  read -ern 1
+  # Clear the image.
+  printf '6;%s;%s;%s;%s\n3;' "${X_POS:-0}" "${Y_POS:-0}" "$WIDTH" "$HEIGHT" | "$w3m" &>/dev/null
+  clear_screen
+  return "${exitCode:-$?}"
 }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# execute function
+main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
 
-# Variable needed for centering image.
-HALF_HEIGHT=$(expr $HEIGHT / 2)
-HALF_WIDTH=$(expr $WIDTH / 2)
-HALF_IMG_HEIGHT=$(expr $img_height / 2)
-HALF_IMG_WIDTH=$(expr $img_width / 2)
-X_POS=$(expr $HALF_WIDTH - $HALF_IMG_WIDTH)
-Y_POS=$(expr $HALF_HEIGHT - $HALF_IMG_HEIGHT)
-
-clear_screen
-# Hide the cursor.
-printf '\e[?25l'
-
-# Display the image.
-printf '0;1;%s;%s;%s;%s;;;;;%s\n3;\n4\n' ${X_POS:-0} ${Y_POS:-0} "$img_width" "$img_height" "${CACHE:-$1}" | "$w3m" &>/dev/null
-
-# Wait for user input.
-read -ern 1
-
-# Clear the image.
-printf '6;%s;%s;%s;%s\n3;' "${X_POS:-0}" "${Y_POS:-0}" "$WIDTH" "$HEIGHT" | "$w3m" &>/dev/null
-
-clear_screen
diff --git a/bin/image b/bin/image
--- a/bin/image
+++ b/bin/image
@@ -1,41 +1,79 @@
 #!/usr/bin/env bash
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 PROG="image"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
-
+SRC_DIR="${BASH_SOURCE%/*}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 021020210301-git
+##@Version       : 031520211806-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
-# @License       : LICENSE.md
-# @ReadME        : README.md
+# @License       : WTFPL
+# @ReadME        : image --help
 # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Saturday, Mar 06, 2021 02:52 EST
+# @Created       : Monday, Mar 15, 2021 18:06 EDT
 # @File          : image
 # @Description   : lf image preview script
 # @TODO          :
 # @Other         :
 # @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-ID_PREVIEW="preview"
-__draw() {
-  declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW" [x]="$3" [y]="$4" [max_width]="$5" [max_height]="$6" [path]="$2")
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
+else
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# helper function
+__version() { app_version; }
+__help() {
+  app_help "Usage: image  -  image --version"  \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function
+main() {
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  case $1 in
+    -v | --version) __version ;;
+    -h | --help) __help ;;
+  esac
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Required app check
+  cmd_exists --error bash ueberzug || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  ID_PREVIEW="preview"
+  __draw() {
+    declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW" [x]="$3" [y]="$4" [max_width]="$5" [max_height]="$6" [path]="$2")
   }
   case "$1" in
-  "clear")
-    declare -p -A cmd=([action]=remove [identifier]="$ID_PREVIEW") >"$FIFO_UEBERZUG"
+    "clear")
+      declare -p -A cmd=([action]=remove [identifier]="$ID_PREVIEW") >"$FIFO_UEBERZUG"
     ;;
-  "draw")
-    __draw >"$FIFO_UEBERZUG" 2>/dev/null
+    "draw")
+      __draw >"$FIFO_UEBERZUG" 2>/dev/null
     ;;
-  "*") echo "Unknown command: '$1', '$2'" ;;
+    "*") echo "Unknown command: '$1', '$2'";exit 1 ;;
   esac
+  return "${exitCode:-$?}"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# execute function
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
 
diff --git a/bin/preview b/bin/preview
--- a/bin/preview
+++ b/bin/preview
@@ -1,89 +1,129 @@
 #!/usr/bin/env bash
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 PROG="preview"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
-
+SRC_DIR="${BASH_SOURCE%/*}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 021020210301-git
+##@Version       : 031520211811-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
-# @License       : LICENSE.md
-# @ReadME        : README.md
+# @License       : WTFPL
+# @ReadME        : preview --help
 # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Saturday, Mar 06, 2021 02:52 EST
+# @Created       : Monday, Mar 15, 2021 18:11 EDT
 # @File          : preview
 # @Description   : lf preview script
 # @TODO          :
 # @Other         :
 # @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Clear the last preview (if any)
-~/.local/bin/image clear
-TMPDIR="${TMP:-/tmp}"
-FILE_PATH="${1}"
-IMAGE_CACHE_PATH="$(mktemp "$TMPDIR/cache.XXXXX")"
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
+else
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# helper function
+__version() { app_version; }
+__help() {
+  app_help "Usage: preview  -  preview --version"  \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function
+main() {
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  case $1 in
+    -v | --version) __version ;;
+    -h | --help) __help ;;
+  esac
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Required app check
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  # Clear the last preview (if any)
+  $HOME/.local/bin/image clear
+  TMPDIR="${TMP:-/tmp}"
+  FILE_PATH="${1}"
+  IMAGE_CACHE_PATH="$(mktemp "$TMPDIR/cache.XXXXX")"
+  # Calculate where the image should be placed on the screen.
+  num=$(printf "%0.f\n" "$(echo "$(tput cols) / 2" | bc)")
+  numb=$(printf "%0.f\n" "$(echo "$(tput cols) - $num - 1" | bc)")
+  numc=$(printf "%0.f\n" "$(echo "$(tput lines) - 2" | bc)")
+  case "$1" in
+    application/font*|application/*opentype)
+      preview_png="$TMPDIR/$(basename "${IMAGE_CACHE_PATH%.*}").png"
+      if fontimage -o "${preview_png}" \
+        --pixelsize "120" \
+        --fontname \
+        --pixelsize "80" \
+        --text "  ABCDEFGHIJKLMNOPQRSTUVWXYZ  " \
+        --text "  abcdefghijklmnopqrstuvwxyz  " \
+        --text "  0123456789.:,;(*!?') ff fl fi ffi ffl  " \
+        --text "  The quick brown fox jumps over the lazy dog.  " \
+        "${FILE_PATH}";
+      then
+        convert -- "${preview_png}" "${IMAGE_CACHE_PATH}" && rm "${preview_png}" && exit 0
+      else
+        exit 1
+      fi
+    ;;
+    *.tgz | *.tar.gz) tar tzf "$1" ;;
+    *.tar.bz2 | *.tbz2) tar tjf "$1" ;;
+    *.tar.txz | *.txz) xz --list "$1" ;;
+    *.tar) tar tf "$1" ;;
+    *.zip | *.jar | *.war | *.ear | *.oxt) unzip -l "$1" ;;
+    *.rar) unrar l "$1" ;;
+    *.7z) 7z l "$1" ;;
+    *.[1-8]) man "$1" | col -b ;;
+    *.o) nm "$1" | less ;;
+    *.torrent) transmission-show "$1" ;;
+    *.iso) iso-info --no-header -l "$1" ;;
+    *odt,*.ods,*.odp,*.sxw) odt2txt "$1" ;;
+    *.doc) catdoc "$1" ;;
+    *.docx) docx2txt "$1" - ;;
+    *.csv) cat "$1" | sed s/,/\\n/g ;;
+    *.pdf)
+	    CACHE=$(mktemp /tmp/thumbcache.XXXXX)
+	    pdftoppm -png -f 1 -singlefile "$1" "$CACHE"
+	    ~/.local/bin/image draw "$CACHE.png" $num 1 $numb $numc 2>/dev/null
+	  ;;
+    *.epub)
+	    CACHE=$(mktemp /tmp/thumbcache.XXXXX)
+	    epub-thumbnailer "$1" "$CACHE" 1024
+	    ~/.local/bin/image draw "$CACHE" $num 1 $numb $numc 2>/dev/null
+	  ;;
+    *.bmp | *.jpg | *.jpeg | *.png | *.xpm | .face)
+	    ~/.local/bin/image draw "$1" $num 1 $numb $numc 2>/dev/null
+	  ;;
+    *.wav | *.mp3 | *.flac | *.m4a | *.wma | *.ape | *.ac3 | *.og[agx] | *.spx | *.opus | *.as[fx] | *.flac) exiftool "$1" ;;
+    *.avi | *.mp4 | *.wmv | *.dat | *.3gp | *.ogv | *.mkv | *.mpg | *.mpeg | *.vob | *.fl[icv] | *.m2v | *.mov | *.webm | *.ts | *.mts | *.m4v | *.r[am] | *.qt | *.divx)
+	    CACHE=$(mktemp /tmp/thumbcache.XXXXX)
+	    ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
+	    ~/.local/bin/image draw "$CACHE" $num 1 $numb $numc 2>/dev/null
+	  ;;
+    *) highlight --out-format ansi "$1" 2>/dev/null || cat "$1" ;;
+  esac
+  return ${exitCode:-$?}
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# execute function
+main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
 
-# Calculate where the image should be placed on the screen.
-num=$(printf "%0.f\n" "$(echo "$(tput cols) / 2" | bc)")
-numb=$(printf "%0.f\n" "$(echo "$(tput cols) - $num - 1" | bc)")
-numc=$(printf "%0.f\n" "$(echo "$(tput lines) - 2" | bc)")
-
-case "$1" in
-application/font*|application/*opentype)
-  preview_png="$TMPDIR/$(basename "${IMAGE_CACHE_PATH%.*}").png"
-  if fontimage -o "${preview_png}" \
-  --pixelsize "120" \
-  --fontname \
-  --pixelsize "80" \
-  --text "  ABCDEFGHIJKLMNOPQRSTUVWXYZ  " \
-  --text "  abcdefghijklmnopqrstuvwxyz  " \
-  --text "  0123456789.:,;(*!?') ff fl fi ffi ffl  " \
-  --text "  The quick brown fox jumps over the lazy dog.  " \
-  "${FILE_PATH}";
-  then
-    convert -- "${preview_png}" "${IMAGE_CACHE_PATH}" && rm "${preview_png}" && exit 0
-  else
-    exit 1
-  fi
-;;
-*.tgz | *.tar.gz) tar tzf "$1" ;;
-*.tar.bz2 | *.tbz2) tar tjf "$1" ;;
-*.tar.txz | *.txz) xz --list "$1" ;;
-*.tar) tar tf "$1" ;;
-*.zip | *.jar | *.war | *.ear | *.oxt) unzip -l "$1" ;;
-*.rar) unrar l "$1" ;;
-*.7z) 7z l "$1" ;;
-*.[1-8]) man "$1" | col -b ;;
-*.o) nm "$1" | less ;;
-*.torrent) transmission-show "$1" ;;
-*.iso) iso-info --no-header -l "$1" ;;
-*odt,*.ods,*.odp,*.sxw) odt2txt "$1" ;;
-*.doc) catdoc "$1" ;;
-*.docx) docx2txt "$1" - ;;
-*.csv) cat "$1" | sed s/,/\\n/g ;;
-*.pdf)
-	CACHE=$(mktemp /tmp/thumbcache.XXXXX)
-	pdftoppm -png -f 1 -singlefile "$1" "$CACHE"
-	~/.local/bin/image draw "$CACHE.png" $num 1 $numb $numc 2>/dev/null
-	;;
-*.epub)
-	CACHE=$(mktemp /tmp/thumbcache.XXXXX)
-	epub-thumbnailer "$1" "$CACHE" 1024
-	~/.local/bin/image draw "$CACHE" $num 1 $numb $numc 2>/dev/null
-	;;
-*.bmp | *.jpg | *.jpeg | *.png | *.xpm | .face)
-	~/.local/bin/image draw "$1" $num 1 $numb $numc 2>/dev/null
-	;;
-*.wav | *.mp3 | *.flac | *.m4a | *.wma | *.ape | *.ac3 | *.og[agx] | *.spx | *.opus | *.as[fx] | *.flac) exiftool "$1" ;;
-*.avi | *.mp4 | *.wmv | *.dat | *.3gp | *.ogv | *.mkv | *.mpg | *.mpeg | *.vob | *.fl[icv] | *.m2v | *.mov | *.webm | *.ts | *.mts | *.m4v | *.r[am] | *.qt | *.divx)
-	CACHE=$(mktemp /tmp/thumbcache.XXXXX)
-	ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
-	~/.local/bin/image draw "$CACHE" $num 1 $numb $numc 2>/dev/null
-	;;
-*) highlight --out-format ansi "$1" 2>/dev/null || cat "$1" ;;
-esac
